baseURL = "https://morven.life/"
languageCode = "en-us"
title = "Morven's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = true

[author]
  name = "Morven's Life"
  homepage = "https://morven.life/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2

[permalinks]
    post = "/blog/:title/"

[params]
# disqus = "morvencao" # disqus account name
# extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-53624533-8"></script><script src="https://joway.io/analytics.js"></script>'
# extraBody = '<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>'
# postAds = '<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-6400651395935595" data-ad-slot="5705651853" data-ad-format="auto" data-full-width-responsive="true"></ins>'
lazyImage = true
description = ""
favicon = "/favicon.ico"
[[params.socials]]
name = "About Me"
link = "/common/about/"
